#!/usr/bin/env php
<?php

defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

$config = require(__DIR__ . '/vendor/kozhindev/yii-steroids/backend/boot/bootstrap.php');
require __DIR__ . '/app/core/base/Yii.php';

// Run application
$application = new \steroids\base\ConsoleApplication($config);
$exitCode = $application->run();
exit($exitCode);